version: '3'
services:
  flask-app:
    build: .
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"