version: '3'
services:
  flask-app:
    build: .
    volumes:
      - "./:/hello-world-flask"
    ports:
      - "5001:5001"
    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: 1
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
